<Bio>:
    orientation: 'vertical'
    size_hint_y: None
    width: '55dp'
    elevation: 0
    theme_bg_color: 'Custom'
    text_color: 1, 1, 1, 1
    md_bg_color: 1, 1, 1, 1
    padding: 20

    MDRelativeLayout:
        MDBoxLayout:
            adaptive_height: True


            MDLabel:
                text: root.bio
                halign: 'justify'
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
